Allow passing language as parameter to avoid dialog prompting. Save /tmp/ipbx.lang if failure to set issabelPBX language so we can set it later

diff --git a/issabel-change-language b/issabel-change-language
--- a/issabel-change-language
+++ b/issabel-change-language
@@ -2,7 +2,7 @@
 function check_dialog()
 {
     if ! dialog &> /dev/null
-    then 
+    then
         echo "ERROR: dialog binary not found."
         exit 1
     fi
@@ -21,41 +21,8 @@ function logo()
          --infobox " O @ @\n @ @ O\n @ O O\n   O\nIssabel" \
         7 11
 }
-check_dialog
-source /etc/issabel.conf
-if [ -z $mysqlrootpwd ]
-then
-    echo "ERROR: Cannot load /etc/issabel.conf"
-    exit 1
-fi
-check_database
 
-currentLang=$(sqlite3 /var/www/db/settings.db "select value from settings where key='language'")
-langselected_en=on
-langselected_es=off
-langselected_br=off
-langselected_fr=off
-langselected_fa=off
-
-if [ "x$currentLang" != "x" ];then 
-langselected_en=off
-declare langselected_${currentLang}=on
-fi
-
-selLang=$((dialog --backtitle "Issabel" --no-tags \
---radiolist "Select PBX language:" 15 40 10 \
- en "English" $langselected_en \
- es "Spanish" $langselected_es \
- pt_BR "Portuguese(BR)" $langselected_br \
- fr "French" $langselected_fr \
- pr "Persian" $langselected_fa \
- > /dev/tty) 2>&1)
-if [ -z $selLang ]
-then
-    #No language selected
-    exit 2
-fi
-
+function set_lang_variables() {
 #Set *non standard* GUI languages
 case $selLang in
     pt_BR)
@@ -89,17 +56,24 @@ case $selLang in
         ipbxLang=$selLang
     ;;
 esac
+}
 
+function set_language()
+{
 (
   sqlite3 /var/www/db/settings.db "update settings set value='$webLang' where key='language'"
   if [ -f /usr/local/fop2/fop2settings.db ]
   then
       sqlite3 /usr/local/fop2/fop2settings.db "update setup set value=\"'$fopLang'\" WHERE extension='SETTINGS' and context='GENERAL' and parameter='language'";
   fi
-  mysql -uroot -p$mysqlrootpwd asterisk -e "REPLACE INTO sipsettings(keyword,data) VALUES('sip_language','$selLang');"
-  mysql -uroot -p$mysqlrootpwd asterisk -e "REPLACE INTO iaxsettings(keyword,data) VALUES('iax_language','$selLang');"
-  mysql -uroot -p$mysqlrootpwd asterisk -e "REPLACE INTO pjsipsettings(keyword,data) VALUES('sip_language','$selLang');"
-  mysql -uroot -p$mysqlrootpwd asterisk -e "REPLACE INTO issabelpbx_settings(keyword,value,type,defaultval,category,name,description) VALUES('LANGUAGE','$ipbxLang','text','en_EN','GUI Behavior','Language','General Language Setting for IssabelPBX');"
+  mysql -uroot -p$mysqlrootpwd asterisk -e "REPLACE INTO sipsettings(keyword,data) VALUES('sip_language','$selLang');" &> /dev/null
+  mysql -uroot -p$mysqlrootpwd asterisk -e "REPLACE INTO iaxsettings(keyword,data) VALUES('iax_language','$selLang');" &> /dev/null
+  mysql -uroot -p$mysqlrootpwd asterisk -e "REPLACE INTO pjsipsettings(keyword,data) VALUES('sip_language','$selLang');" &> /dev/null
+  mysql -uroot -p$mysqlrootpwd asterisk -e "REPLACE INTO issabelpbx_settings(keyword,value,type,defaultval,category,name,description) VALUES('LANGUAGE','$ipbxLang','text','en_EN','GUI Behavior','Language','General Language Setting for IssabelPBX');" &> /dev/null
+  if [ $? -gt 0 ]; then
+      # Failed to set issabelPBX settings, store selection in temp for later
+      write_selection
+  fi
   #DAHDI
   DAHDI_CFG="/etc/asterisk/chan_dahdi.conf"
   if grep -q "language=" $DAHDI_CFG
@@ -110,6 +84,9 @@ esac
   fi
   sed -i "s/.*defaultlanguage.*/defaultlanguage=$selLang/" /etc/asterisk/asterisk.conf
 ) &> /dev/null
+}
+
+function reload_amportal() {
 logo
 if ! amportal a r &> /dev/null
 then
@@ -119,4 +96,78 @@ then
 else
     clear
 fi
+}
 
+function write_selection() {
+    echo "{\"webLang\":\"$webLang\",\"fopLang\":\"$fopLang\",\"ipbxLang\":\"$ipbxLang\"}" >/tmp/ipbx.lang
+}
+
+# Loads mysql root password
+source /etc/issabel.conf
+
+if [ -z $mysqlrootpwd ]
+then
+    echo "ERROR: Cannot load /etc/issabel.conf"
+    exit 1
+fi
+
+
+# Start MAIN section
+
+if [ $# -eq 0 ];
+then
+
+# No argument supplied, dialog asking for language
+
+check_dialog
+check_database
+
+if [ -f /var/www/db/settings.db ]; then
+    currentLang=$(sqlite3 /var/www/db/settings.db "select value from settings where key='language'")
+else
+    currentLang=""
+fi
+
+langselected_en=on
+langselected_es=off
+langselected_br=off
+langselected_fr=off
+langselected_fa=off
+
+if [ "x$currentLang" != "x" ]; then
+    langselected_en=off
+    declare langselected_${currentLang}=on
+fi
+
+selLang=$((dialog --backtitle "Issabel" --no-tags \
+--radiolist "Select PBX language:" 15 40 10 \
+ en "English" $langselected_en \
+ es "Spanish" $langselected_es \
+ pt_BR "Portuguese(BR)" $langselected_br \
+ fr "French" $langselected_fr \
+ pr "Persian" $langselected_fa \
+ > /dev/tty) 2>&1)
+if [ -z $selLang ]
+then
+    #No language selected
+    exit 2
+fi
+
+set_lang_variables
+set_language
+reload_amportal
+
+else
+    # language argument passed, if valid just apply changes
+    valid_lang="es en fr pt_BR pr"
+    selLang=$1
+    if [[ $valid_lang =~ (^|[[:space:]])$selLang($|[[:space:]]) ]]; then
+	set_lang_variables
+	echo $webLang
+	echo $fopLang
+	echo $ipbxLang
+        set_language
+        reload_amportal
+    fi
+
+fi
